local-zone: "doubleclick.net" refuse
local-zone: "googlesyndication.com" refuse
local-zone: "liftoff.io" refuse
local-zone: "liftoff-creatives.io" refuse
local-zone: "organicowner.com" refuse
local-zone: "adrevenue.appsflyersdk.com" refuse
local-zone: "vungle.com" refuse
local-zone: "applovin.com" refuse
local-zone: "applvn.com" refuse
local-zone: "pangle.io" refuse
local-zone: "tiktokpangle.us" refuse
local-zone: "adrta.com" refuse
local-zone: "googleadservices.com" refuse
local-zone: "adx.opera.com" refuse
