# Unbound configuration file for Debian.
#
# See the unbound.conf(5) man page.
#
# See /usr/share/doc/unbound/examples/unbound.conf for a commented
# reference config file.
#
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"

#rpz:
#	name: rpz.zone
#	zonefile: db.rpz
#	rpz-action-override: cname
#	rpz-cname-override: "localhost."

server:
	# Include blocklist
	include: "/etc/unbound/blocklists.conf"

	# Interface binding
	interface: 0.0.0.0
	interface: ::

	# Access control
	# Loopback
	access-control: 127.0.0.0/8 allow
	access-control: ::1 allow

	# RFC1918
	access-control: 10.0.0.0/8 allow
	access-control: 172.16.0.0/12 allow
	access-control: 192.168.0.0/16 allow

	# Public Address
	access-control: 100.64.0.0/24 allow
	access-control: 2001::/64 allow

	# Default policy
	access-control: 0.0.0.0/0 deny_non_local
	access-control: ::/0 deny_non_local

	# Server options
	num-threads: 8
	ip-transparent: yes
	ip-freebind: yes
	hide-version: yes

	prefetch: yes
	deny-any: yes
	module-config: "respip validator iterator"

	rrset-cache-size: 100m
	msg-cache-size: 200m

	statistics-cumulative: yes
	extended-statistics: yes
	statistics-inhibit-zero: no

#auth-zone:
#	name: 0.168.192.in-addr.arpa
#	zonefile: db.192.168.0
