# Unbound configuration file for Debian.
#
# See the unbound.conf(5) man page.
#
# See /usr/share/doc/unbound/examples/unbound.conf for a commented
# reference config file.
#
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"

forward-zone:
    name: "."
    forward-addr: 1.1.1.1

forward-zone:
    name: "@main-domain."
    forward-addr: 1.1.1.1

rpz:
	name: rpz.zone
	zonefile: db.rpz
	rpz-action-override: cname
	rpz-cname-override: "@restrict-domain."

server:
	# Include blocklist
	include: "/etc/unbound/blocklists.conf"

	# Interface binding
	interface: 0.0.0.0
	interface: ::

	# Access control
	# Loopback
	access-control: 127.0.0.0/8 allow
	access-control: ::1 allow

	# RFC1918
	access-control: 10.0.0.0/8 allow
	access-control: 172.16.0.0/12 allow
	access-control: 192.168.0.0/16 allow

	# Default policy
	access-control: 0.0.0.0/0 deny_non_local
	access-control: ::/0 deny_non_local

	# Server options
	num-threads: @threads
	hide-version: yes

	prefetch: yes
	deny-any: yes
	module-config: "respip validator iterator"

	rrset-cache-size: 100m
	msg-cache-size: 200m

	statistics-cumulative: yes
	extended-statistics: yes
	statistics-inhibit-zero: no

auth-zone:
	name: @main-domain
	zonefile: db.@main-domain
